-- 00_setup.sql: one-time network access for Nimble. Run as ACCOUNTADMIN.
-- Replace <<NIMBLE_API_KEY>> with the customer's Nimble API key before running (deploy.py does this from a local secret).
CREATE DATABASE IF NOT EXISTS NIMBLE_INTEL;
CREATE SCHEMA IF NOT EXISTS NIMBLE_INTEL.CORE;
CREATE OR REPLACE NETWORK RULE NIMBLE_INTEL.CORE.NIMBLE_RULE
  TYPE = HOST_PORT MODE = EGRESS VALUE_LIST = ('sdk.nimbleway.com');
CREATE OR REPLACE SECRET NIMBLE_INTEL.CORE.NIMBLE_KEY
  TYPE = GENERIC_STRING SECRET_STRING = '<<NIMBLE_API_KEY>>' COMMENT = 'Nimble API key used by the company intelligence skill';
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION NIMBLE_INTEL_ACCESS
  ALLOWED_NETWORK_RULES = (NIMBLE_INTEL.CORE.NIMBLE_RULE)
  ALLOWED_AUTHENTICATION_SECRETS = (NIMBLE_INTEL.CORE.NIMBLE_KEY) ENABLED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS NIMBLE_INTEL_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
