-- 02_procs.sql: the four entry points. The Python code lives in @NIMBLE_INTEL.CORE.CODE/nimble_intel.py.
CREATE OR REPLACE PROCEDURE NIMBLE_INTEL.CORE.INSTALL_AGENTS()
  RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION = '3.11' PACKAGES = ('snowflake-snowpark-python', 'requests')
  IMPORTS = ('@NIMBLE_INTEL.CORE.CODE/nimble_intel.py') HANDLER = 'nimble_intel.install_agents'
  EXTERNAL_ACCESS_INTEGRATIONS = (NIMBLE_INTEL_ACCESS) SECRETS = ('nimble_key' = NIMBLE_INTEL.CORE.NIMBLE_KEY)
  EXECUTE AS OWNER;

CREATE OR REPLACE PROCEDURE NIMBLE_INTEL.CORE.RESEARCH(COMPANY STRING, DOMAIN STRING, MARKET STRING DEFAULT 'US', INCLUDE_MAPS BOOLEAN DEFAULT NULL)
  RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION = '3.11' PACKAGES = ('snowflake-snowpark-python', 'requests')
  IMPORTS = ('@NIMBLE_INTEL.CORE.CODE/nimble_intel.py') HANDLER = 'nimble_intel.start'
  EXTERNAL_ACCESS_INTEGRATIONS = (NIMBLE_INTEL_ACCESS) SECRETS = ('nimble_key' = NIMBLE_INTEL.CORE.NIMBLE_KEY)
  COMMENT = 'Starts Nimble company intelligence for one company: account brief first, then brand signals, AI answers, search, news, Reddit and optional Google Maps.'
  EXECUTE AS OWNER;

CREATE OR REPLACE PROCEDURE NIMBLE_INTEL.CORE.POLL()
  RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION = '3.11' PACKAGES = ('snowflake-snowpark-python', 'requests')
  IMPORTS = ('@NIMBLE_INTEL.CORE.CODE/nimble_intel.py') HANDLER = 'nimble_intel.poll'
  EXTERNAL_ACCESS_INTEGRATIONS = (NIMBLE_INTEL_ACCESS) SECRETS = ('nimble_key' = NIMBLE_INTEL.CORE.NIMBLE_KEY)
  EXECUTE AS OWNER;

CREATE OR REPLACE PROCEDURE NIMBLE_INTEL.CORE.BUILD(COMPANY_ID STRING)
  RETURNS VARIANT LANGUAGE PYTHON RUNTIME_VERSION = '3.11' PACKAGES = ('snowflake-snowpark-python', 'requests')
  IMPORTS = ('@NIMBLE_INTEL.CORE.CODE/nimble_intel.py') HANDLER = 'nimble_intel.build'
  EXTERNAL_ACCESS_INTEGRATIONS = (NIMBLE_INTEL_ACCESS) SECRETS = ('nimble_key' = NIMBLE_INTEL.CORE.NIMBLE_KEY)
  EXECUTE AS OWNER;
